{
 "title": "Main dashboard - monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS POST /user/search",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/user/search\",method=\"POST\"}[10s]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{status=~\"5.*\",route=\"/user/search\",method=\"POST\"}[10s]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "RPS POST /user/search_id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/user/search_id\",method=\"POST\"}[10s]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{status=~\"5.*\",route=\"/user/search_id\",method=\"POST\"}[10s]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  { "title": "API Register user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RPS POST /user/register",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/user/register\",method=\"POST\"}[10s]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{status=~\"5.*\",route=\"/user/register\",method=\"POST\"}[10s]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LETENCY POST /user/register",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"POST\",route=\"/user/register\"}[10s]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"POST\",route=\"/user/register\"}[10s]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"POST\",route=\"/user/register\"}[10s]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"POST\",route=\"/user/register\"}[10s]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "API Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "RPS GET /health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/health\",method=\"GET\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{status=~\"5.*\",method=\"GET\",route=\"/health\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LETENCY GET /health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/health\"}[1m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/health\"}[1m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/health\"}[1m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/health\"}[1m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  }
 ]
}